### ISSUE TITLE
Entire trace was found to be busy. Audit key: time-to-interactive.

### ISSUE THREAD

**Issue by akella** [paulirish/pwmetrics#109] opened 2017-04-23 12:47 UTC
This is a great tool! Hope it will grow with functionality!

Meanwhile getting this error on my website, i guess it has something to do with youtube iframe
```
pwmetrics http://cssing.org.ua                                   2.1m
Launching Chrome
  ✘ Error: Unable to complete run 1 of 1 due to Audit error: Entire trace was found to be busy. Audit key: time-to-interactive.
```
Hope this will help to improve the tool!
Thank you.

**Comment by pedro93** [comment] 2017-04-23 13:35
Hey, thank you for feedback :)
Can you reproduce this error in lighthouse? Pwmetrics is nothing more than a wrapper on top of it.

**Comment by akella** [comment] 2017-04-23 15:43
Thank you for fast feedback!
Just generated report using chrome plugin (thats what you meant?) 
http://take.ms/bNd3Z

Tried running pwmetrics again, with plugin installed - same error.

**Comment by pedro93** [comment] 2017-04-23 17:01
Lighthouse chrome plugin or npm module is fine for this :)

I noticed the same problem happened in lighthouse plugin, I don't think it's a pwmetrics problem. Perhaps lighthouse is not (yet?) equipped to handle something in the website you tried to test. 

I would suggest opening an issue in the [lighthouse repo](https://github.com/GoogleChrome/lighthouse) and see what the developers say.

In the meantime I will close this issue as it appears out of scope. Feel free to reopen if necessary :)

**Closed by pedro93** 2017-04-23 17:01 UTC

**Comment by denar90** [comment] 2017-04-23 20:26
@akella thx for reporting this one. After running your site via Lighthouse (using cli) I faced no problems (TTI for you site was +990ms), probably it's because we are using Paul's fork. Tomorrow I'll make some investigations about it...
