### ISSUE TITLE
Process.exit

### ISSUE THREAD

**Issue by Bubbit** [paulirish/pwmetrics#88] opened 2017-04-03 06:35 UTC
What is the reason process.exit() is required at the end of the run? https://github.com/paulirish/pwmetrics/blob/master/recipes/gulp/gulpfile.js#L48
I'm trying to integrate pwmetrics as part of my CI-chain, but currently the only solution is to spawn it in a different process.

**Comment by denar90** [comment] 2017-04-03 08:39
We just wanted to and gulp task after `pwmetrics` finished it's job. But you can solve this case in other way, due to needs of your CI and gulp process.

**Comment by Bubbit** [comment] 2017-04-03 08:45
I'm trying to figure out which process isn't exiting properly as it should finish without me having to call a process.exit. I don't want to fix it by spawning a child process, but it's currently the only solution

**Comment by denar90** [comment] 2017-04-03 09:02
Does it exit correctly without `pwmetrics` ? Wanna figure out if problem caused by us.

**Comment by Bubbit** [comment] 2017-04-03 09:03
Yes it does exit correctly.

**Comment by denar90** [comment] 2017-04-03 09:04
Can you share code, plz?

**Comment by Bubbit** [comment] 2017-04-03 09:13
https://github.com/Bubbit/pwmetrics/blob/master/recipes/gulp/gulpfile.js

Doesn't close properly

**Comment by denar90** [comment] 2017-04-03 09:22
ok, I'll look at it but a bit later...

**Comment by pedro93** [comment] 2017-04-03 10:26
Hello @Bubbit thank you for posting this issue. 

I will have a look to try when I have more time and understand why, I am not sure if this is because of ```pwmetrics``` or because of ```lighthouse```. 
In the meantime I would suggest using ```child_process``` like so:

https://gist.github.com/pedro93/efb78fd310b1d1dcda656ad4aaabf413

Basically:
1.) Setup a local web server.
2.) Execute pwmetrics as a child process, give it a callback function so your server knows when the tests have concluded.
3.) Clean up the server.

**Comment by pedro93** [comment] 2017-04-03 13:44
@Bubbit @denar90 After digging around a little I found no particular reason why pwmetrics would maintain the process live. I checked in lighthouse and noticed the same happening: https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/gulp

@Bubbit May I suggest you ask about ```process.exit(0)``` in the lighthouse repository? You can link back to this issue as needed. 

I will close this this comment with a will not fix as this is not of the responsability of pwmetrics as far as I can see. Feel free to reopen if you disagree.

**Closed by pedro93** 2017-04-03 13:44 UTC

**Comment by Bubbit** [comment] 2017-04-04 12:40
I filled the issue at the lighthouse repository, but it's not due to lighthouse. 

So I went back and did some more investigation, the process doesn't exit due to the chart output.
I'm using the default macos terminal, so I don't know if it's due to that or not.

For now my problem is fixed as I'll just pass the json output value, but I don't think this is intended.
But I have prepared a pull request just in case

**Comment by pedro93** [comment] 2017-04-04 13:01
@Bubbit thank for the investigation. I've tried it in my local version and it seems to work well. I will accept the request and then close this issue. Quick question, did you see a correct visual graph using the macos default terminal?

**Comment by Bubbit** [comment] 2017-04-04 13:10
@pedro93 Sadly no, still the same as https://github.com/paulirish/pwmetrics/issues/1

**Comment by pedro93** [comment] 2017-04-04 13:30
Solved via https://github.com/paulirish/pwmetrics/pull/89. @Bubbit if you have anything more to say with regards to the chart or do find something please use the https://github.com/paulirish/pwmetrics/issues/1 issue. Thank you very much for your help 👍
