### ISSUE TITLE
Output chart misaligned with the MacOS terminal

### ISSUE THREAD

**Issue by tleunen** [paulirish/pwmetrics#1] opened 2016-08-24 12:44 UTC
With Node 6.4, with zsh and the default macos terminal. Funny enough (or not), I don't have the issue with hyperterm (also with zsh).

<img width="938" alt="screen shot 2016-08-24 at 8 37 39 am" src="https://cloud.githubusercontent.com/assets/1972567/17930814/1d6a8994-69d6-11e6-91c3-f3acb477e12a.png">

**Comment by paulirish** [comment] 2016-08-27 04:00
ouch, bummer. I imagine then that the https://github.com/andrewjstone/cli-chart module would be generaly failing for you.

**Comment by paulirish** [comment] 2016-10-16 13:47
ive reproduced this too. default terminal has problems with cli-chart
but hyperterm and iterm2 are fine.

i dont know.. :/ 

in the future i think we'll have to replace cli-chart.

**Comment by denar90** [comment] 2016-11-23 13:27
@paulirish @samccone what would you like to replace `cli-chart` with? Do you have anything in mind?

**Comment by samccone** [comment] 2016-11-23 16:25
hmm anything really, we looked at the logic a while back and seems pretty straightforward logic wise... So if nothing fits the bill feel to roll a version :)

**Comment by denar90** [comment] 2016-11-26 21:09
I haven't find any better libs for reaching current needs, hence fix might be done in scope of`cli-chart`...

**Comment by denar90** [comment] 2016-12-06 21:06
Some idea came up. What if, instead of showing chart in terminal just draw it in browser.  Nevertheless we are opening it to measure site perf, so at the end of the process we can show some fancy results in same window or something, using d3 for example.

**Comment by paulirish** [comment] 2016-12-11 23:54
I'm open to using the browser, however it's nice to see this stuff in travis if you're running it there.

**Comment by denar90** [comment] 2016-12-12 06:38
We can show in browser by default and console output for CI. But doing this looks like major change...

**Comment by shellscape** [comment] 2017-02-22 18:24
Is there any stop-gap so folks using terminal can see properly formatted output on MacOS?

**Comment by denar90** [comment] 2017-02-22 21:26
Sorry, we didn't have time to look at this one. @shellscape are you interested to help us?

**Comment by shellscape** [comment] 2017-02-22 23:00
I could take a look at this early next week. I'm presently slammed.

**Comment by paulirish** [comment] 2017-02-23 05:06
Cheers. We've since forked the chart module to be local, so we can make whatever changes we like.
Happy for someone to take a look!

**Comment by pedro93** [comment] 2017-03-25 13:16
@paulirish @shellscape @denar90 I've been having a crack at this but have been unsuccessful. Whilst we have no better solution or a fix to the chart what to you think about simply outputting text? 

We can work with the visual output that [getMessageWithPrefix](https://github.com/paulirish/pwmetrics/blob/master/lib/utils/messages.js#L90) gives us. If a user sets expectations the output is even better. Thoughts?

**Comment by exogen** [comment] 2017-04-19 20:11
I did some debugging and it appears that `push()` and `pop()` from `charm` just don't work on this terminal. The cursor will still be positioned at the last move/write even after calling `pop()`. I'm not sure what the actual lower level fix is, but it's not too difficult to work around this in `lib/chart` by just using the various positioning commands to navigate back to the origin (or wherever) instead of push/pop.

**Comment by exogen** [comment] 2017-04-19 20:20
Update: Changing them all to `push(true)` and `pop(true)` appears to fix it. The parameter is `withAttributes`, which I don't fully understand, but it works. Will have to make sure this doesn't break other terminals.

![screen shot 2017-04-19 at 1 18 58 pm](https://cloud.githubusercontent.com/assets/53522/25200388/fccf274c-2502-11e7-9782-abc841e6437c.png)

**Comment by exogen** [comment] 2017-04-19 23:32
Fixed in #102.

**Comment by pedro93** [comment] 2017-04-20 04:34
@tleunen can you confirm that with https://github.com/paulirish/pwmetrics/pull/102 the issue is fixed on your end? If so I will close this issue.

**Comment by tleunen** [comment] 2017-04-20 04:43
Looks like it's works fine with latest master :)
![image](https://cloud.githubusercontent.com/assets/1972567/25213937/29db2c9a-2549-11e7-8105-4d411924945e.png)

**Comment by pedro93** [comment] 2017-04-20 05:15
Amazing, closing the issue then ;)

**Closed by pedro93** 2017-04-20 05:15 UTC
Labels: bug, help wanted
